/*
 * This source file was generated by the Gradle 'init' task
 */
package com.example.Player;

import com.example.Player.sample.Player;
import com.example.Player.sample1.CricketPlayer;

public class Main {
    

    public static void main(String[] args) {
       Player player=new Player("India","International Player","senior","15 years","Ms Dhoni",43,"23-05-1982","graduate","male");
       System.out.println(player);
       CricketPlayer cp=new CricketPlayer(11,2,"wicket keeper","India","International Player","senior","15 years","Ms Dhoni",43,"23-05-1982","graduate","male");
       System.out.println(cp);
    }
}
