/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package myfirstgui;

/**
 *
 * @author sonam
 */
public class Fun extends javax.swing.JFrame {

   double num1=0,num2=0;
   String operator="";
    /**
     * Creates new form Fun
     */
    public Fun() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jbuttonClear = new javax.swing.JButton();
        t1 = new javax.swing.JTextField();
        jbutton0 = new javax.swing.JButton();
        jbutton3 = new javax.swing.JButton();
        jbutton6 = new javax.swing.JButton();
        jbutton1 = new javax.swing.JButton();
        jbutton4 = new javax.swing.JButton();
        jbutton7 = new javax.swing.JButton();
        jbutton2 = new javax.swing.JButton();
        jbutton5 = new javax.swing.JButton();
        jbutton8 = new javax.swing.JButton();
        jbuttonAdd = new javax.swing.JButton();
        jbutton9 = new javax.swing.JButton();
        jbuttonSub = new javax.swing.JButton();
        jbuttonMul = new javax.swing.JButton();
        jbuttonDiv = new javax.swing.JButton();
        jbuttonResult = new javax.swing.JButton();
        jbuttonDEL = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(51, 255, 0));

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));
        jPanel1.setBorder(new javax.swing.border.MatteBorder(null));

        jbuttonClear.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        jbuttonClear.setText("Clear");
        jbuttonClear.setToolTipText("press Mouse's left Button");
        jbuttonClear.setBorder(new javax.swing.border.MatteBorder(null));
        jbuttonClear.setPreferredSize(new java.awt.Dimension(72, 34));
        jbuttonClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbuttonClearActionPerformed(evt);
            }
        });

        t1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        t1.setBorder(new javax.swing.border.MatteBorder(null));
        t1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t1ActionPerformed(evt);
            }
        });

        jbutton0.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jbutton0.setText("0");
        jbutton0.setBorder(new javax.swing.border.MatteBorder(null));
        jbutton0.setPreferredSize(new java.awt.Dimension(34, 34));
        jbutton0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbutton0ActionPerformed(evt);
            }
        });

        jbutton3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jbutton3.setText("3");
        jbutton3.setBorder(new javax.swing.border.MatteBorder(null));
        jbutton3.setPreferredSize(new java.awt.Dimension(34, 34));
        jbutton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbutton3ActionPerformed(evt);
            }
        });

        jbutton6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jbutton6.setText("6");
        jbutton6.setBorder(new javax.swing.border.MatteBorder(null));
        jbutton6.setPreferredSize(new java.awt.Dimension(34, 34));
        jbutton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbutton6ActionPerformed(evt);
            }
        });

        jbutton1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jbutton1.setText("1");
        jbutton1.setBorder(new javax.swing.border.MatteBorder(null));
        jbutton1.setPreferredSize(new java.awt.Dimension(34, 34));
        jbutton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbutton1ActionPerformed(evt);
            }
        });

        jbutton4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jbutton4.setText("4");
        jbutton4.setBorder(new javax.swing.border.MatteBorder(null));
        jbutton4.setPreferredSize(new java.awt.Dimension(34, 34));
        jbutton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbutton4ActionPerformed(evt);
            }
        });

        jbutton7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jbutton7.setText("7");
        jbutton7.setBorder(new javax.swing.border.MatteBorder(null));
        jbutton7.setPreferredSize(new java.awt.Dimension(34, 34));
        jbutton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbutton7ActionPerformed(evt);
            }
        });

        jbutton2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jbutton2.setText("2");
        jbutton2.setBorder(new javax.swing.border.MatteBorder(null));
        jbutton2.setPreferredSize(new java.awt.Dimension(34, 34));
        jbutton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbutton2ActionPerformed(evt);
            }
        });

        jbutton5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jbutton5.setText("5");
        jbutton5.setBorder(new javax.swing.border.MatteBorder(null));
        jbutton5.setPreferredSize(new java.awt.Dimension(34, 34));
        jbutton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbutton5ActionPerformed(evt);
            }
        });

        jbutton8.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jbutton8.setText("8");
        jbutton8.setBorder(new javax.swing.border.MatteBorder(null));
        jbutton8.setPreferredSize(new java.awt.Dimension(34, 34));
        jbutton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbutton8ActionPerformed(evt);
            }
        });

        jbuttonAdd.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jbuttonAdd.setText("+");
        jbuttonAdd.setBorder(new javax.swing.border.MatteBorder(null));
        jbuttonAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbuttonAddActionPerformed(evt);
            }
        });

        jbutton9.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jbutton9.setText("9");
        jbutton9.setBorder(new javax.swing.border.MatteBorder(null));
        jbutton9.setPreferredSize(new java.awt.Dimension(34, 34));
        jbutton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbutton9ActionPerformed(evt);
            }
        });

        jbuttonSub.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jbuttonSub.setText("-");
        jbuttonSub.setBorder(new javax.swing.border.MatteBorder(null));
        jbuttonSub.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbuttonSubActionPerformed(evt);
            }
        });

        jbuttonMul.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jbuttonMul.setText("*");
        jbuttonMul.setBorder(new javax.swing.border.MatteBorder(null));
        jbuttonMul.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbuttonMulActionPerformed(evt);
            }
        });

        jbuttonDiv.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jbuttonDiv.setText("/");
        jbuttonDiv.setBorder(new javax.swing.border.MatteBorder(null));
        jbuttonDiv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbuttonDivActionPerformed(evt);
            }
        });

        jbuttonResult.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jbuttonResult.setText("=");
        jbuttonResult.setBorder(new javax.swing.border.MatteBorder(null));
        jbuttonResult.setPreferredSize(new java.awt.Dimension(32, 34));
        jbuttonResult.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbuttonResultActionPerformed(evt);
            }
        });

        jbuttonDEL.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jbuttonDEL.setText("DEL");
        jbuttonDEL.setBorder(new javax.swing.border.MatteBorder(null));
        jbuttonDEL.setPreferredSize(new java.awt.Dimension(72, 34));
        jbuttonDEL.setVerifyInputWhenFocusTarget(false);
        jbuttonDEL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbuttonDELActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(t1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jbutton4, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jbutton5, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jbutton6, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(jbutton1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jbutton2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jbutton3, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jbutton7, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jbutton8, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(32, 32, 32)
                                        .addComponent(jbutton9, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(40, 40, 40))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jbutton0, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jbuttonDEL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jbuttonAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jbuttonSub, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jbuttonMul, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jbuttonDiv, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 16, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(jbuttonClear, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jbuttonResult, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(t1, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbutton1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbutton2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbuttonAdd)
                    .addComponent(jbutton3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbutton4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbutton5, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbuttonSub)
                    .addComponent(jbutton6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbutton7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbutton8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbuttonMul)
                    .addComponent(jbutton9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jbuttonDEL, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jbuttonDiv, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jbutton0, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jbuttonResult, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbuttonClear, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(131, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(84, 84, 84))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbuttonClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbuttonClearActionPerformed
        // TODO add your handling code here:
        //System.out.println("You are clicking me!");
      // System.out.println( jTextField1.getText());
     // count++;
     // if(count<4){
     // jTextField1.setText("You are clicking me! count:"+count);
    //  }
     // else
      //{
       //   StringBuffer sb = new StringBuffer(jTextField1.getText());
      //
          // jTextField1.setText(sb.reverse().toString());
          
         
    //  }
    t1.setText("");
    }//GEN-LAST:event_jbuttonClearActionPerformed

    private void t1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t1ActionPerformed
             // TODO add your handling code here:
    }//GEN-LAST:event_t1ActionPerformed

    private void jbutton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbutton6ActionPerformed
         t1.setText(t1.getText()+"6");
// TODO add your handling code here:
    }//GEN-LAST:event_jbutton6ActionPerformed

    private void jbutton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbutton4ActionPerformed
        t1.setText(t1.getText()+"4");
        // TODO add your handling code here:
    }//GEN-LAST:event_jbutton4ActionPerformed

    private void jbutton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbutton7ActionPerformed
       t1.setText(t1.getText()+"7");
        // TODO add your handlng code here:
    }//GEN-LAST:event_jbutton7ActionPerformed

    private void jbutton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbutton2ActionPerformed
         t1.setText(t1.getText()+"2");
// TODO add your handling code here:
    }//GEN-LAST:event_jbutton2ActionPerformed

    private void jbutton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbutton5ActionPerformed
         t1.setText(t1.getText()+"5");
// TODO add your handling code here:
    }//GEN-LAST:event_jbutton5ActionPerformed

    private void jbutton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbutton8ActionPerformed
         t1.setText(t1.getText()+"8");
// TODO add your handling code here:
    }//GEN-LAST:event_jbutton8ActionPerformed

    private void jbuttonAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbuttonAddActionPerformed
                                                  
    num1 = Integer.parseInt(t1.getText());  
    operator = "+";                         
    t1.setText(t1.getText() + "+");        


    }//GEN-LAST:event_jbuttonAddActionPerformed

    private void jbutton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbutton9ActionPerformed
         t1.setText(t1.getText()+"9");
// TODO add your handling code here:
    }//GEN-LAST:event_jbutton9ActionPerformed

    private void jbuttonSubActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbuttonSubActionPerformed
       
        num1=Integer.parseInt(t1.getText());
         operator="-";
        t1.setText(t1.getText()+"-");
         
        // TODO add your handling code here:
    }//GEN-LAST:event_jbuttonSubActionPerformed

    private void jbuttonMulActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbuttonMulActionPerformed
       
         
        num1=Double.parseDouble(t1.getText());
         operator="*"; 
        t1.setText(t1.getText()+"*");
        
        // TODO add your handling code here:
    }//GEN-LAST:event_jbuttonMulActionPerformed

    private void jbuttonDivActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbuttonDivActionPerformed
         
         num1=Double.parseDouble(t1.getText());
          operator="/";
         t1.setText(t1.getText()+"/");
        
         
// TODO add your handling code here:
    }//GEN-LAST:event_jbuttonDivActionPerformed

    private void jbutton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbutton1ActionPerformed
        t1.setText("1");
        // TODO add your handling code here:
    }//GEN-LAST:event_jbutton1ActionPerformed

    private void jbuttonDELActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbuttonDELActionPerformed
      String str=t1.getText();
        t1.setText(str.substring(0,str.length()-1));
        // TODO add your handling code here:
    }//GEN-LAST:event_jbuttonDELActionPerformed

    private void jbutton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbutton3ActionPerformed
   t1.setText(t1.getText()+"3");
        // TODO add your handling code here:
    }//GEN-LAST:event_jbutton3ActionPerformed

    private void jbutton0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbutton0ActionPerformed
        t1.setText(t1.getText()+"0");
        // TODO add your handling code here:
    }//GEN-LAST:event_jbutton0ActionPerformed

    private void jbuttonResultActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbuttonResultActionPerformed
    
   String input = t1.getText().trim();

    if (input.contains("+")) {
        String[] parts = input.split("\\+");
        int result = Integer.parseInt(parts[0]) + Integer.parseInt(parts[1]);
        t1.setText(String.valueOf(result));
    } else if (input.contains("-")) {
        String[] parts = input.split("-");
        int result = Integer.parseInt(parts[0]) - Integer.parseInt(parts[1]);
        t1.setText(String.valueOf(result));
    } else if (input.contains("*")) {
        String[] parts = input.split("\\*");
        Integer result = Integer.parseInt(parts[0]) * Integer.parseInt(parts[1]);
t1.setText(String.valueOf(result));
    } else if (input.contains("/")) {
        String[] parts = input.split("/");
        double result = Double.parseDouble(parts[0]) / Double.parseDouble(parts[1]);
      t1.setText(String.valueOf(result));
    } else {
        t1.setText("Invalid Input");
    }

    }//GEN-LAST:event_jbuttonResultActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Fun.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Fun.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Fun.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Fun.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Fun().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton jbutton0;
    private javax.swing.JButton jbutton1;
    private javax.swing.JButton jbutton2;
    private javax.swing.JButton jbutton3;
    private javax.swing.JButton jbutton4;
    private javax.swing.JButton jbutton5;
    private javax.swing.JButton jbutton6;
    private javax.swing.JButton jbutton7;
    private javax.swing.JButton jbutton8;
    private javax.swing.JButton jbutton9;
    private javax.swing.JButton jbuttonAdd;
    private javax.swing.JButton jbuttonClear;
    private javax.swing.JButton jbuttonDEL;
    private javax.swing.JButton jbuttonDiv;
    private javax.swing.JButton jbuttonMul;
    private javax.swing.JButton jbuttonResult;
    private javax.swing.JButton jbuttonSub;
    private javax.swing.JTextField t1;
    // End of variables declaration//GEN-END:variables
     // private int count;
  
}
